/*
 * SPDX-FileCopyrightText: 2026 ESP32-S3 USB DAC Project
 * SPDX-License-Identifier: MIT
 */

#ifndef _PREFERENCES_UI_HTML_H_
#define _PREFERENCES_UI_HTML_H_

static const char s_preferences_ui_html[] = "<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0,user-scalable=no\">\n"
"<title>// DSP32-S3 // HARDWARE PREFERENCES //</title>\n"
"<style>\n"
":root{\n"
"  --bg:#000000;\n"
"  --fg:#ffffff;\n"
"  --dim:#666666;\n"
"  --faint:#222222;\n"
"  --mono:ui-monospace,'Courier New',Consolas,monospace;\n"
"}\n"
"*{box-sizing:border-box;margin:0;padding:0}\n"
"body{\n"
"  background:var(--bg);\n"
"  color:var(--fg);\n"
"  font-family:var(--mono);\n"
"  font-size:12px;\n"
"  line-height:1.4;\n"
"  padding:16px;\n"
"  max-width:760px;\n"
"  margin:0 auto;\n"
"  letter-spacing:1px;\n"
"}\n"
"a{color:var(--fg);text-decoration:none;transition:background .1s,color .1s}\n"
"header{\n"
"  display:flex;\n"
"  justify-content:space-between;\n"
"  align-items:center;\n"
"  border:1px solid var(--fg);\n"
"  padding:12px 14px;\n"
"  margin-bottom:14px;\n"
"  gap:10px;\n"
"}\n"
"h1{\n"
"  font-size:14px;\n"
"  font-weight:700;\n"
"  letter-spacing:2px;\n"
"  text-transform:uppercase;\n"
"  display:flex;\n"
"  align-items:center;\n"
"  gap:10px;\n"
"}\n"
".badge{\n"
"  font-size:10px;\n"
"  padding:2px 6px;\n"
"  border:1px solid var(--fg);\n"
"  background:#000;\n"
"  color:var(--fg);\n"
"  text-transform:uppercase;\n"
"}\n"
".section{\n"
"  border:1px solid var(--fg);\n"
"  padding:14px;\n"
"  margin-bottom:14px;\n"
"  background:#000;\n"
"}\n"
".sec-title{\n"
"  font-size:11px;\n"
"  text-transform:uppercase;\n"
"  letter-spacing:2px;\n"
"  margin-bottom:12px;\n"
"  padding-bottom:6px;\n"
"  border-bottom:1px solid var(--faint);\n"
"  color:var(--fg);\n"
"}\n"
".grid-2{display:grid;grid-template-columns:1fr 1fr;gap:12px}\n"
".field{margin-bottom:12px}\n"
"label{\n"
"  display:block;\n"
"  font-size:10px;\n"
"  color:var(--dim);\n"
"  margin-bottom:4px;\n"
"  letter-spacing:1px;\n"
"  text-transform:uppercase;\n"
"}\n"
"input[type=number],input[type=text],input[type=password]{\n"
"  width:100%;\n"
"  background:#000000;\n"
"  border:1px solid var(--dim);\n"
"  color:var(--fg);\n"
"  padding:8px 10px;\n"
"  font-family:var(--mono);\n"
"  font-size:12px;\n"
"  border-radius:0;\n"
"  outline:none;\n"
"  letter-spacing:1px;\n"
"  transition:border-color .15s;\n"
"}\n"
"input:focus{border-color:var(--fg)}\n"
"button, .btn{\n"
"  background:#000000;\n"
"  border:1px solid var(--fg);\n"
"  color:var(--fg);\n"
"  padding:8px 16px;\n"
"  font-family:var(--mono);\n"
"  font-size:11px;\n"
"  font-weight:700;\n"
"  letter-spacing:1px;\n"
"  cursor:pointer;\n"
"  border-radius:0;\n"
"  text-transform:uppercase;\n"
"  outline:none;\n"
"  transition:background .1s,color .1s;\n"
"}\n"
"button:hover, .btn:hover{\n"
"  background:var(--fg);\n"
"  color:var(--bg);\n"
"}\n"
"footer{\n"
"  text-align:center;\n"
"  color:var(--dim);\n"
"  font-size:10px;\n"
"  margin-top:24px;\n"
"  padding:14px 0;\n"
"  border-top:1px solid var(--dim);\n"
"  letter-spacing:1.5px;\n"
"}\n"
"@media(max-width:600px){.grid-2{grid-template-columns:1fr}}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<header>\n"
"  <div>\n"
"    <h1>// DSP32-S3 // <span class=\"badge\">PREFERENCES</span></h1>\n"
"  </div>\n"
"  <a href=\"/\"><button>[ &lt; DASHBOARD ]</button></a>\n"
"</header>\n"
"\n"
"<div class=\"section\">\n"
"  <div class=\"sec-title\">// 01. I2S AUDIO HARDWARE PINOUT (DAC / AMP) //</div>\n"
"  <div class=\"grid-2\">\n"
"    <div class=\"field\">\n"
"      <label for=\"pin-bck\">BCK (BIT CLOCK) GPIO</label>\n"
"      <input type=\"number\" id=\"pin-bck\" min=\"0\" max=\"48\" value=\"10\">\n"
"    </div>\n"
"    <div class=\"field\">\n"
"      <label for=\"pin-din\">DIN (DATA IN ON DAC) GPIO</label>\n"
"      <input type=\"number\" id=\"pin-din\" min=\"0\" max=\"48\" value=\"11\">\n"
"    </div>\n"
"  </div>\n"
"  <div class=\"grid-2\">\n"
"    <div class=\"field\">\n"
"      <label for=\"pin-ws\">WS / LCK (WORD SELECT) GPIO</label>\n"
"      <input type=\"number\" id=\"pin-ws\" min=\"0\" max=\"48\" value=\"12\">\n"
"    </div>\n"
"  </div>\n"
"  <div style=\"color:var(--dim);font-size:10px;margin-top:4px\">\n"
"    // DEFAULT HARDWARE PINOUT: BCK = 10, DIN = 11, WS = 12 //\n"
"  </div>\n"
"</div>\n"
"\n"
"<div class=\"section\">\n"
"  <div class=\"sec-title\">// 02. PERIPHERALS, DISPLAY &amp; INDICATORS //</div>\n"
"  <div class=\"grid-2\">\n"
"    <div class=\"field\">\n"
"      <label for=\"pin-scl\">OLED SCL GPIO (-1 TO DISABLE)</label>\n"
"      <input type=\"number\" id=\"pin-scl\" min=\"-1\" max=\"48\" value=\"9\">\n"
"    </div>\n"
"    <div class=\"field\">\n"
"      <label for=\"pin-sda\">OLED SDA GPIO (-1 TO DISABLE)</label>\n"
"      <input type=\"number\" id=\"pin-sda\" min=\"-1\" max=\"48\" value=\"8\">\n"
"    </div>\n"
"  </div>\n"
"  <div class=\"grid-2\">\n"
"    <div class=\"field\">\n"
"      <label for=\"pin-led\">NEOPIXEL RGB LED GPIO (-1 TO DISABLE)</label>\n"
"      <input type=\"number\" id=\"pin-led\" min=\"-1\" max=\"48\" value=\"48\">\n"
"    </div>\n"
"    <div class=\"field\">\n"
"      <label for=\"pin-btn\">BOOT BUTTON GPIO (-1 TO DISABLE)</label>\n"
"      <input type=\"number\" id=\"pin-btn\" min=\"-1\" max=\"48\" value=\"0\">\n"
"    </div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<div class=\"section\">\n"
"  <div class=\"sec-title\">// 03. WI-FI SOFTAP CONFIGURATION //</div>\n"
"  <div class=\"grid-2\">\n"
"    <div class=\"field\">\n"
"      <label for=\"wifi-ssid\">NETWORK SSID</label>\n"
"      <input type=\"text\" id=\"wifi-ssid\" maxlength=\"31\" value=\"ESP32-DSP-DAC\">\n"
"    </div>\n"
"    <div class=\"field\">\n"
"      <label for=\"wifi-pass\">WPA2 PASSWORD (MIN 8 CHARS)</label>\n"
"      <input type=\"text\" id=\"wifi-pass\" maxlength=\"63\" value=\"12345678\">\n"
"    </div>\n"
"  </div>\n"
"  <div class=\"grid-2\">\n"
"    <div class=\"field\">\n"
"      <label for=\"wifi-ch\">WI-FI RADIO CHANNEL (1 - 13)</label>\n"
"      <input type=\"number\" id=\"wifi-ch\" min=\"1\" max=\"13\" value=\"1\">\n"
"    </div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<div class=\"section\">\n"
"  <div class=\"sec-title\">// 04. DISPLAY &amp; VISUALIZER CALIBRATION //</div>\n"
"  <div class=\"field\" style=\"margin-bottom:12px\">\n"
"    <label style=\"display:flex;align-items:center;gap:8px;cursor:pointer;color:var(--fg);font-size:11px\">\n"
"      <input type=\"checkbox\" id=\"oled-enabled\" checked style=\"width:16px;height:16px;accent-color:var(--fg);cursor:pointer\">\n"
"      <span>ENABLE SSD1306 OLED DISPLAY</span>\n"
"    </label>\n"
"    <div style=\"color:var(--dim);font-size:10px;margin-top:2px\">// Toggle display power to sleep screen and free I2C / Core 0 CPU //</div>\n"
"  </div>\n"
"  <div class=\"grid-2\">\n"
"    <div class=\"field\">\n"
"      <label for=\"oled-fps\">OLED HARDWARE REFRESH RATE (FPS: 15 - 60)</label>\n"
"      <input type=\"number\" id=\"oled-fps\" min=\"15\" max=\"60\" value=\"30\">\n"
"      <div style=\"color:var(--dim);font-size:10px;margin-top:2px\">// 15-30 FPS = 400kHz I2C &bull; 35-60 FPS = 800kHz FAST+ //</div>\n"
"    </div>\n"
"    <div class=\"field\">\n"
"      <label for=\"web-scope-fps\">WEB UI SCOPE REFRESH RATE (FPS: 10 - 60)</label>\n"
"      <input type=\"number\" id=\"web-scope-fps\" min=\"10\" max=\"60\" value=\"30\">\n"
"      <div style=\"color:var(--dim);font-size:10px;margin-top:2px\">// Dashboard vector oscilloscope polling rate //</div>\n"
"    </div>\n"
"  </div>\n"
"  <div class=\"grid-2\" style=\"margin-top:8px\">\n"
"    <div class=\"field\">\n"
"      <label for=\"scope-gain\">OSCILLOSCOPE SENSITIVITY: <span id=\"scope-gain-val\">2.00x</span></label>\n"
"      <input type=\"range\" id=\"scope-gain\" min=\"0.25\" max=\"10.0\" step=\"0.25\" value=\"2.0\" style=\"width:100%;accent-color:var(--fg);height:28px\" oninput=\"document.getElementById('scope-gain-val').innerText=parseFloat(this.value).toFixed(2)+'x'\">\n"
"      <div style=\"color:var(--dim);font-size:10px;margin-top:2px\">// Amplifies scope motion at quiet listening levels //</div>\n"
"    </div>\n"
"    <div class=\"field\">\n"
"      <label for=\"scope-pre-vol\">SIGNAL TAP POINT</label>\n"
"      <select id=\"scope-pre-vol\" style=\"width:100%;background:#000;border:1px solid var(--dim);color:var(--fg);padding:8px 10px;font-family:var(--mono);font-size:12px;border-radius:0;outline:none;\">\n"
"        <option value=\"1\">PRE-VOLUME (STUDIO / IMMUNE TO VOLUME LEVEL)</option>\n"
"        <option value=\"0\">POST-VOLUME (MASTER VOLUME ATTENUATES SCOPE)</option>\n"
"      </select>\n"
"      <div style=\"color:var(--dim);font-size:10px;margin-top:2px\">// Pre-Volume keeps full dynamics at whisper volumes //</div>\n"
"    </div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<div class=\"section\" style=\"display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:10px\">\n"
"  <button onclick=\"resetDefaults()\">[ RESET TO DEFAULTS ]</button>\n"
"  <button id=\"btn-save\" onclick=\"saveAndRestart()\">[ SAVE CONFIGURATION ]</button>\n"
"</div>\n"
"\n"
"<div id=\"reboot-box\" style=\"display:none;background:#000;border:1px solid var(--fg);color:var(--fg);padding:14px;text-align:center;margin-top:14px\">\n"
"  <div id=\"reboot-title\" style=\"font-size:13px;font-weight:700;margin-bottom:6px\">// SETTINGS SAVED //</div>\n"
"  <div id=\"reboot-msg\" style=\"color:var(--dim);font-size:11px\">Rebooting into new configuration in 3 seconds...</div>\n"
"</div>\n"
"\n"
"<footer>\n"
"  // ESP32-S3 SUPERMINI &bull; DYNAMIC HARDWARE PINOUT &bull; NVS ENGINE //\n"
"</footer>\n"
"\n"
"<script>\n"
"function loadPrefs() {\n"
"  fetch('/api/preferences')\n"
"    .then(r => r.json())\n"
"    .then(d => {\n"
"      if (d) {\n"
"        if (d.i2s_bck_gpio !== undefined) document.getElementById('pin-bck').value = d.i2s_bck_gpio;\n"
"        if (d.i2s_din_gpio !== undefined) document.getElementById('pin-din').value = d.i2s_din_gpio;\n"
"        if (d.i2s_ws_gpio !== undefined) document.getElementById('pin-ws').value = d.i2s_ws_gpio;\n"
"        if (d.oled_scl_gpio !== undefined) document.getElementById('pin-scl').value = d.oled_scl_gpio;\n"
"        if (d.oled_sda_gpio !== undefined) document.getElementById('pin-sda').value = d.oled_sda_gpio;\n"
"        if (d.neopixel_gpio !== undefined) document.getElementById('pin-led').value = d.neopixel_gpio;\n"
"        if (d.boot_button_gpio !== undefined) document.getElementById('pin-btn').value = d.boot_button_gpio;\n"
"        if (d.wifi_ssid) document.getElementById('wifi-ssid').value = d.wifi_ssid;\n"
"        if (d.wifi_pass !== undefined) document.getElementById('wifi-pass').value = d.wifi_pass;\n"
"        if (d.wifi_channel) document.getElementById('wifi-ch').value = d.wifi_channel;\n"
"        if (d.oled_enabled !== undefined) document.getElementById('oled-enabled').checked = !!d.oled_enabled;\n"
"        if (d.oled_fps !== undefined) document.getElementById('oled-fps').value = d.oled_fps;\n"
"        if (d.web_scope_fps !== undefined) document.getElementById('web-scope-fps').value = d.web_scope_fps;\n"
"        if (d.scope_gain !== undefined) {\n"
"          document.getElementById('scope-gain').value = d.scope_gain;\n"
"          document.getElementById('scope-gain-val').innerText = parseFloat(d.scope_gain).toFixed(2) + 'x';\n"
"        }\n"
"        if (d.scope_pre_vol !== undefined) document.getElementById('scope-pre-vol').value = d.scope_pre_vol ? '1' : '0';\n"
"      }\n"
"    }).catch(e => console.error('Failed to load preferences:', e));\n"
"}\n"
"\n"
"function saveAndRestart() {\n"
"  const cfg = {\n"
"    i2s_bck_gpio: parseInt(document.getElementById('pin-bck').value),\n"
"    i2s_din_gpio: parseInt(document.getElementById('pin-din').value),\n"
"    i2s_ws_gpio: parseInt(document.getElementById('pin-ws').value),\n"
"    oled_scl_gpio: parseInt(document.getElementById('pin-scl').value),\n"
"    oled_sda_gpio: parseInt(document.getElementById('pin-sda').value),\n"
"    neopixel_gpio: parseInt(document.getElementById('pin-led').value),\n"
"    boot_button_gpio: parseInt(document.getElementById('pin-btn').value),\n"
"    wifi_ssid: document.getElementById('wifi-ssid').value,\n"
"    wifi_pass: document.getElementById('wifi-pass').value,\n"
"    wifi_channel: parseInt(document.getElementById('wifi-ch').value),\n"
"    oled_enabled: document.getElementById('oled-enabled').checked,\n"
"    oled_fps: parseInt(document.getElementById('oled-fps').value) || 30,\n"
"    web_scope_fps: parseInt(document.getElementById('web-scope-fps').value) || 30,\n"
"    scope_gain: parseFloat(document.getElementById('scope-gain').value) || 2.0,\n"
"    scope_pre_vol: document.getElementById('scope-pre-vol').value === '1'\n"
"  };\n"
"\n"
"  document.getElementById('btn-save').disabled = true;\n"
"  fetch('/api/preferences', {\n"
"    method: 'POST',\n"
"    headers: {'Content-Type': 'application/json'},\n"
"    body: JSON.stringify(cfg)\n"
"  }).then(r => r.json()).then(res => {\n"
"    if (res.status === 'ok') {\n"
"      const box = document.getElementById('reboot-box');\n"
"      box.style.display = 'block';\n"
"      if (res.reboot) {\n"
"        document.getElementById('reboot-title').innerText = '// HARDWARE PINS CHANGED //';\n"
"        let count = 4;\n"
"        setInterval(() => {\n"
"          count--;\n"
"          if (count > 0) {\n"
"            document.getElementById('reboot-msg').innerText = `// Rebooting in ${count}s... Reconnecting to dashboard //`;\n"
"          } else {\n"
"            window.location.href = '/';\n"
"          }\n"
"        }, 1000);\n"
"      } else {\n"
"        document.getElementById('reboot-title').innerText = '// CONFIGURATION APPLIED LIVE //';\n"
"        document.getElementById('reboot-msg').innerText = res.message || 'Display & calibration settings updated in RAM and NVS.';\n"
"        document.getElementById('btn-save').disabled = false;\n"
"        setTimeout(() => { box.style.display = 'none'; }, 3500);\n"
"      }\n"
"    } else {\n"
"      alert('Save failed: ' + (res.message || 'Error'));\n"
"      document.getElementById('btn-save').disabled = false;\n"
"    }\n"
"  }).catch(e => {\n"
"    alert('Network error saving preferences');\n"
"    document.getElementById('btn-save').disabled = false;\n"
"  });\n"
"}\n"
"\n"
"function resetDefaults() {\n"
"  if (!confirm('Reset all hardware pinout and Wi-Fi preferences to factory defaults (BCK=10, DIN=11, WS=12)?')) return;\n"
"  fetch('/api/preferences/reset', {method: 'POST'})\n"
"    .then(r => r.json())\n"
"    .then(() => {\n"
"      alert('Preferences reset to factory defaults. Reloading...');\n"
"      loadPrefs();\n"
"    }).catch(e => alert('Error resetting preferences'));\n"
"}\n"
"\n"
"window.onload = loadPrefs;\n"
"</script>\n"
"</body>\n"
"</html>\n";

#endif /* _PREFERENCES_UI_HTML_H_ */
