/*
 * SPDX-FileCopyrightText: 2026 ESP32-S3 USB DAC Project
 * SPDX-License-Identifier: MIT
 */

#ifndef _WEB_UI_HTML_H_
#define _WEB_UI_HTML_H_

static const char s_web_ui_html[] = "<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0,user-scalable=no\">\n"
"<title>// DSP32-S3 // VIB-RIBBON AUDIO //</title>\n"
"<style>\n"
":root{\n"
"  --bg:#000000;\n"
"  --fg:#ffffff;\n"
"  --dim:#666666;\n"
"  --faint:#222222;\n"
"  --mono:ui-monospace,'Courier New',Consolas,monospace;\n"
"}\n"
"*{box-sizing:border-box;margin:0;padding:0}\n"
"body{\n"
"  background:var(--bg);\n"
"  color:var(--fg);\n"
"  font-family:var(--mono);\n"
"  font-size:12px;\n"
"  line-height:1.4;\n"
"  padding:16px;\n"
"  max-width:980px;\n"
"  margin:0 auto;\n"
"  letter-spacing:1px;\n"
"}\n"
"a{color:var(--fg);text-decoration:none;transition:background .1s,color .1s}\n"
"header{\n"
"  display:flex;\n"
"  flex-wrap:wrap;\n"
"  justify-content:space-between;\n"
"  align-items:center;\n"
"  border:1px solid var(--fg);\n"
"  padding:12px 14px;\n"
"  margin-bottom:14px;\n"
"  gap:12px;\n"
"}\n"
"h1{\n"
"  font-size:15px;\n"
"  font-weight:700;\n"
"  letter-spacing:2px;\n"
"  text-transform:uppercase;\n"
"  display:flex;\n"
"  align-items:center;\n"
"  gap:10px;\n"
"}\n"
".badge{\n"
"  font-size:10px;\n"
"  padding:2px 6px;\n"
"  border:1px solid var(--fg);\n"
"  background:#000;\n"
"  color:var(--fg);\n"
"  text-transform:uppercase;\n"
"}\n"
".top-bar{display:flex;align-items:center;gap:8px;flex-wrap:wrap}\n"
"button, .btn{\n"
"  background:#000000;\n"
"  border:1px solid var(--fg);\n"
"  color:var(--fg);\n"
"  padding:6px 12px;\n"
"  font-family:var(--mono);\n"
"  font-size:11px;\n"
"  font-weight:600;\n"
"  letter-spacing:1px;\n"
"  cursor:pointer;\n"
"  text-transform:uppercase;\n"
"  border-radius:0;\n"
"  outline:none;\n"
"  transition:background .1s,color .1s;\n"
"}\n"
"button:hover, .btn:hover{\n"
"  background:var(--fg);\n"
"  color:var(--bg);\n"
"}\n"
".btn-direct.active{\n"
"  background:var(--fg);\n"
"  color:var(--bg);\n"
"  font-weight:700;\n"
"}\n"
".section{\n"
"  border:1px solid var(--fg);\n"
"  padding:14px;\n"
"  margin-bottom:14px;\n"
"  background:#000;\n"
"}\n"
".sec-title{\n"
"  font-size:11px;\n"
"  text-transform:uppercase;\n"
"  letter-spacing:2px;\n"
"  margin-bottom:12px;\n"
"  padding-bottom:6px;\n"
"  border-bottom:1px solid var(--faint);\n"
"  display:flex;\n"
"  justify-content:space-between;\n"
"  align-items:center;\n"
"  color:var(--fg);\n"
"}\n"
".meter-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}\n"
".meter-box{font-size:11px}\n"
".meter-row{display:flex;align-items:center;gap:8px;margin-top:6px}\n"
".meter-bar-wrap{\n"
"  flex:1;\n"
"  height:10px;\n"
"  background:#000;\n"
"  border:1px solid var(--fg);\n"
"  position:relative;\n"
"  overflow:hidden;\n"
"}\n"
".meter-fill{\n"
"  height:100%;\n"
"  width:0%;\n"
"  background:var(--fg);\n"
"  transition:width .05s linear;\n"
"}\n"
".meter-fill.clip{\n"
"  background:#fff;\n"
"  animation:blink .1s infinite alternate;\n"
"}\n"
"@keyframes blink{from{opacity:1}to{opacity:0.2}}\n"
".meter-val{width:48px;text-align:right;color:var(--fg);font-size:10px}\n"
"\n"
"canvas{\n"
"  width:100%;\n"
"  height:140px;\n"
"  background:#000;\n"
"  border:1px solid var(--fg);\n"
"  display:block;\n"
"}\n"
".eq-sliders{display:grid;grid-template-columns:repeat(10,1fr);gap:4px;margin-top:12px;text-align:center}\n"
".eq-band{font-size:9px;color:var(--dim)}\n"
".eq-band input[type=range]{\n"
"  -webkit-appearance:slider-vertical;\n"
"  writing-mode:bt-lr;\n"
"  height:80px;\n"
"  width:100%;\n"
"  margin:6px 0;\n"
"  accent-color:var(--fg);\n"
"}\n"
".eq-val{color:var(--fg);font-size:10px}\n"
"\n"
".fx-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:12px}\n"
".fx-card{\n"
"  border:1px solid var(--dim);\n"
"  padding:12px;\n"
"  background:#000;\n"
"  transition:border-color .15s;\n"
"}\n"
".fx-card:hover{border-color:var(--fg)}\n"
".fx-head{\n"
"  display:flex;\n"
"  justify-content:space-between;\n"
"  align-items:center;\n"
"  margin-bottom:8px;\n"
"  padding-bottom:4px;\n"
"  border-bottom:1px dashed var(--dim);\n"
"}\n"
".fx-name{font-size:11px;font-weight:700;letter-spacing:1px}\n"
"input[type=checkbox]{\n"
"  accent-color:var(--fg);\n"
"  width:14px;\n"
"  height:14px;\n"
"  cursor:pointer;\n"
"}\n"
".fx-ctrl{margin-top:8px}\n"
".ctrl-row{display:flex;justify-content:space-between;font-size:10px;color:var(--dim);margin-bottom:2px}\n"
".ctrl-val{color:var(--fg)}\n"
"input[type=range]{\n"
"  width:100%;\n"
"  accent-color:var(--fg);\n"
"  cursor:pointer;\n"
"  height:2px;\n"
"  background:var(--dim);\n"
"  outline:none;\n"
"}\n"
".row-flex{display:flex;align-items:center;gap:10px}\n"
".select-custom{\n"
"  background:#000;\n"
"  border:1px solid var(--fg);\n"
"  color:var(--fg);\n"
"  padding:6px 10px;\n"
"  font-family:var(--mono);\n"
"  font-size:11px;\n"
"  border-radius:0;\n"
"  outline:none;\n"
"}\n"
"footer{\n"
"  text-align:center;\n"
"  color:var(--dim);\n"
"  font-size:10px;\n"
"  margin-top:24px;\n"
"  padding:14px 0;\n"
"  border-top:1px solid var(--dim);\n"
"  letter-spacing:1.5px;\n"
"}\n"
"@media(max-width:600px){\n"
"  .meter-grid{grid-template-columns:1fr}\n"
"  .eq-sliders{grid-template-columns:repeat(5,1fr);row-gap:12px}\n"
"}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<header>\n"
"  <div>\n"
"    <h1>// DSP32-S3 // <span class=\"badge\" id=\"st-rate\">48 kHz / 16-bit</span></h1>\n"
"    <div style=\"color:var(--dim);font-size:10px;margin-top:4px\">RIBBON VECTOR AUDIO // PCM5102A + MAX97220</div>\n"
"  </div>\n"
"  <div class=\"top-bar\">\n"
"    <button class=\"btn-direct\" id=\"btn-bypass\" onclick=\"toggleBypass()\">[ BIT-PERFECT: OFF ]</button>\n"
"    <a href=\"/preferences.html\"><button>[ PREF ]</button></a>\n"
"    <a href=\"/ota.html\"><button>[ OTA ]</button></a>\n"
"  </div>\n"
"</header>\n"
"\n"
"<div class=\"section\">\n"
"  <div class=\"sec-title\"><span>// 01. LATENCY &amp; DMA BUFFER //</span><span id=\"lbl-buf-val\">128 samples (Safe)</span></div>\n"
"  <div class=\"row-flex\">\n"
"    <input type=\"range\" id=\"sl-buffer\" min=\"0\" max=\"4\" step=\"1\" value=\"3\" onchange=\"updateBuffer(this.value)\">\n"
"    <span style=\"font-size:11px;width:80px;text-align:right\" id=\"lbl-lat-ms\">~2.7 ms</span>\n"
"  </div>\n"
"</div>\n"
"\n"
"<div class=\"section\">\n"
"  <div class=\"sec-title\"><span>// 02. REAL-TIME VU LEVEL METER //</span><a href=\"/preferences.html\" style=\"font-size:10px;color:var(--dim)\">[ PREFERENCES &gt; ]</a></div>\n"
"  <div class=\"meter-grid\">\n"
"    <div class=\"meter-box\">\n"
"      <div style=\"color:var(--dim);margin-bottom:4px\">INPUT (USB STREAM)</div>\n"
"      <div class=\"meter-row\"><span>L</span><div class=\"meter-bar-wrap\"><div class=\"meter-fill\" id=\"m-in-l\"></div></div><span class=\"meter-val\" id=\"v-in-l\">-&infin;</span></div>\n"
"      <div class=\"meter-row\"><span>R</span><div class=\"meter-bar-wrap\"><div class=\"meter-fill\" id=\"m-in-r\"></div></div><span class=\"meter-val\" id=\"v-in-r\">-&infin;</span></div>\n"
"    </div>\n"
"    <div class=\"meter-box\">\n"
"      <div style=\"color:var(--dim);margin-bottom:4px\">OUTPUT (I2S TO DAC)</div>\n"
"      <div class=\"meter-row\"><span>L</span><div class=\"meter-bar-wrap\"><div class=\"meter-fill\" id=\"m-out-l\"></div></div><span class=\"meter-val\" id=\"v-out-l\">-&infin;</span></div>\n"
"      <div class=\"meter-row\"><span>R</span><div class=\"meter-bar-wrap\"><div class=\"meter-fill\" id=\"m-out-r\"></div></div><span class=\"meter-val\" id=\"v-out-r\">-&infin;</span></div>\n"
"    </div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<div class=\"section\">\n"
"  <div class=\"sec-title\"><span>// 03. NEOPIXEL RGB VISUALIZER (GPIO 48) //</span><span id=\"lbl-led-mode\">VU PEAK</span></div>\n"
"  <div class=\"row-flex\" style=\"gap:6px;flex-wrap:wrap;margin-bottom:12px\">\n"
"    <button id=\"btn-led-0\" onclick=\"setLEDMode(0)\">[ OFF ]</button>\n"
"    <button id=\"btn-led-1\" onclick=\"setLEDMode(1)\">[ VU PEAK ]</button>\n"
"    <button id=\"btn-led-2\" onclick=\"setLEDMode(2)\">[ BASS PULSE ]</button>\n"
"    <button id=\"btn-led-3\" onclick=\"setLEDMode(3)\">[ RAINBOW ]</button>\n"
"    <button id=\"btn-led-4\" onclick=\"setLEDMode(4)\">[ WARM TUBE ]</button>\n"
"    <button id=\"btn-led-5\" onclick=\"setLEDMode(5)\">[ STATUS ]</button>\n"
"  </div>\n"
"  <div class=\"row-flex\">\n"
"    <span style=\"font-size:10px;color:var(--dim);width:90px\">BRIGHTNESS</span>\n"
"    <input type=\"range\" id=\"sl-led-br\" min=\"0\" max=\"100\" value=\"50\" oninput=\"document.getElementById('lbl-led-br').innerText = this.value + '%'\" onchange=\"sendLEDConfig()\">\n"
"    <span style=\"font-size:11px;width:45px;text-align:right\" id=\"lbl-led-br\">50%</span>\n"
"  </div>\n"
"</div>\n"
"\n"
"<div class=\"section\">\n"
"  <div class=\"sec-title\"><span>// 04. 10-BAND PARAMETRIC EQ //</span><span><label style=\"font-size:10px\">ENABLE <input type=\"checkbox\" id=\"chk-eq\" checked onchange=\"sendConfig()\"></label></span></div>\n"
"  <canvas id=\"eq-canvas\"></canvas>\n"
"  <div class=\"eq-sliders\" id=\"eq-controls\"></div>\n"
"</div>\n"
"\n"
"<div class=\"section\">\n"
"  <div class=\"sec-title\">// 05. STUDIO DSP EFFECTS CHAIN //</div>\n"
"  <div class=\"fx-grid\">\n"
"\n"
"    <div class=\"fx-card\">\n"
"      <div class=\"fx-head\"><span class=\"fx-name\">DYNAMIC COMPRESSOR</span><input type=\"checkbox\" id=\"chk-comp\" onchange=\"sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Threshold</span><span class=\"ctrl-val\" id=\"v-comp-t\">-20 dB</span></div><input type=\"range\" id=\"sl-comp-t\" min=\"-60\" max=\"0\" value=\"-20\" oninput=\"upd(this);sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Ratio</span><span class=\"ctrl-val\" id=\"v-comp-r\">4.0:1</span></div><input type=\"range\" id=\"sl-comp-r\" min=\"1\" max=\"20\" step=\"0.5\" value=\"4\" oninput=\"upd(this);sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Attack</span><span class=\"ctrl-val\" id=\"v-comp-a\">15 ms</span></div><input type=\"range\" id=\"sl-comp-a\" min=\"1\" max=\"100\" value=\"15\" oninput=\"upd(this);sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Release</span><span class=\"ctrl-val\" id=\"v-comp-rel\">100 ms</span></div><input type=\"range\" id=\"sl-comp-rel\" min=\"10\" max=\"1000\" value=\"100\" oninput=\"upd(this);sendConfig()\"></div>\n"
"    </div>\n"
"\n"
"    <div class=\"fx-card\">\n"
"      <div class=\"fx-head\"><span class=\"fx-name\">PEAK LIMITER</span><input type=\"checkbox\" id=\"chk-limiter\" checked onchange=\"sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Ceiling</span><span class=\"ctrl-val\" id=\"v-lim-c\">-0.2 dBFS</span></div><input type=\"range\" id=\"sl-lim-c\" min=\"-6\" max=\"-0.1\" step=\"0.1\" value=\"-0.2\" oninput=\"upd(this);sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Release</span><span class=\"ctrl-val\" id=\"v-lim-r\">50 ms</span></div><input type=\"range\" id=\"sl-lim-r\" min=\"10\" max=\"300\" value=\"50\" oninput=\"upd(this);sendConfig()\"></div>\n"
"    </div>\n"
"\n"
"    <div class=\"fx-card\">\n"
"      <div class=\"fx-head\"><span class=\"fx-name\">CASSETTE TAPE EMULATOR</span><input type=\"checkbox\" id=\"chk-tape\" onchange=\"sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Drive / Saturation</span><span class=\"ctrl-val\" id=\"v-tape-d\">20 %</span></div><input type=\"range\" id=\"sl-tape-d\" min=\"0\" max=\"100\" value=\"20\" oninput=\"upd(this);sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Lo-Fi HF Cutoff</span><span class=\"ctrl-val\" id=\"v-tape-hf\">15.0 kHz</span></div><input type=\"range\" id=\"sl-tape-hf\" min=\"4000\" max=\"20000\" step=\"250\" value=\"15000\" oninput=\"upd(this);sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Head Bump (65Hz)</span><span class=\"ctrl-val\" id=\"v-tape-hb\">25 %</span></div><input type=\"range\" id=\"sl-tape-hb\" min=\"0\" max=\"100\" value=\"25\" oninput=\"upd(this);sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Tape Hiss Level</span><span class=\"ctrl-val\" id=\"v-tape-hs\">1 %</span></div><input type=\"range\" id=\"sl-tape-hs\" min=\"0\" max=\"100\" value=\"1\" oninput=\"upd(this);sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Soft Tape Clicks</span><span class=\"ctrl-val\" id=\"v-tape-cr\">5 %</span></div><input type=\"range\" id=\"sl-tape-cr\" min=\"0\" max=\"100\" value=\"5\" oninput=\"upd(this);sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Click Amplitude</span><span class=\"ctrl-val\" id=\"v-tape-cl\">3 %</span></div><input type=\"range\" id=\"sl-tape-cl\" min=\"0\" max=\"100\" value=\"3\" oninput=\"upd(this);sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Wow &amp; Flutter</span><span class=\"ctrl-val\" id=\"v-tape-wf\">10 %</span></div><input type=\"range\" id=\"sl-tape-wf\" min=\"0\" max=\"100\" value=\"10\" oninput=\"upd(this);sendConfig()\"></div>\n"
"      <div style=\"display:flex;gap:4px;margin-top:6px;flex-wrap:wrap\">\n"
"        <button style=\"font-size:8px;padding:3px 6px\" onclick=\"setTapeProfile('type1')\">[ TYPE I ]</button>\n"
"        <button style=\"font-size:8px;padding:3px 6px\" onclick=\"setTapeProfile('type2')\">[ TYPE II ]</button>\n"
"        <button style=\"font-size:8px;padding:3px 6px\" onclick=\"setTapeProfile('lofi')\">[ LO-FI ]</button>\n"
"        <button style=\"font-size:8px;padding:3px 6px\" onclick=\"setTapeProfile('master')\">[ MASTER ]</button>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <div class=\"fx-card\">\n"
"      <div class=\"fx-head\"><span class=\"fx-name\">BITCRUSHER / DOWNSAMPLER</span><input type=\"checkbox\" id=\"chk-bc\" onchange=\"sendConfig()\"></div>\n"
"      <div style=\"display:flex;gap:8px;margin-bottom:8px;font-size:9px;flex-wrap:wrap;border-bottom:1px dashed var(--dim);padding-bottom:6px\">\n"
"        <label style=\"display:flex;align-items:center;gap:3px;cursor:pointer\"><input type=\"checkbox\" id=\"chk-bc-srr\" onchange=\"sendConfig()\"> DOWNSAMPLE</label>\n"
"        <label style=\"display:flex;align-items:center;gap:3px;cursor:pointer\"><input type=\"checkbox\" id=\"chk-bc-q\" onchange=\"sendConfig()\"> QUANTIZE</label>\n"
"        <label style=\"display:flex;align-items:center;gap:3px;cursor:pointer\"><input type=\"checkbox\" id=\"chk-bc-ovf\" onchange=\"sendConfig()\"> OVERFLOW</label>\n"
"        <label style=\"display:flex;align-items:center;gap:3px;cursor:pointer\"><input type=\"checkbox\" id=\"chk-bc-dit\" onchange=\"sendConfig()\"> DITHER</label>\n"
"      </div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Sample Rate Reduction</span><span class=\"ctrl-val\" id=\"v-bc-rate\">8.0 kHz</span></div><input type=\"range\" id=\"sl-bc-rate\" min=\"500\" max=\"48000\" step=\"250\" value=\"8000\" oninput=\"upd(this);sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Bit Depth</span><span class=\"ctrl-val\" id=\"v-bc-bits\">8 bit</span></div><input type=\"range\" id=\"sl-bc-bits\" min=\"2\" max=\"16\" step=\"1\" value=\"8\" oninput=\"upd(this);sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Overflow Drive</span><span class=\"ctrl-val\" id=\"v-bc-ovf\">30 %</span></div><input type=\"range\" id=\"sl-bc-ovf\" min=\"0\" max=\"100\" value=\"30\" oninput=\"upd(this);sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Wet / Dry Mix</span><span class=\"ctrl-val\" id=\"v-bc-mix\">100 %</span></div><input type=\"range\" id=\"sl-bc-mix\" min=\"0\" max=\"100\" value=\"100\" oninput=\"upd(this);sendConfig()\"></div>\n"
"      <div style=\"display:flex;gap:4px;margin-top:6px;flex-wrap:wrap\">\n"
"        <button style=\"font-size:8px;padding:3px 6px\" onclick=\"setCrushProfile('classic')\">[ 8-BIT RETRO ]</button>\n"
"        <button style=\"font-size:8px;padding:3px 6px\" onclick=\"setCrushProfile('srr')\">[ ALIASING ONLY ]</button>\n"
"        <button style=\"font-size:8px;padding:3px 6px\" onclick=\"setCrushProfile('grit')\">[ 12-BIT SAMPLER ]</button>\n"
"        <button style=\"font-size:8px;padding:3px 6px\" onclick=\"setCrushProfile('glitch')\">[ GLITCH OVERFLOW ]</button>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <div class=\"fx-card\">\n"
"      <div class=\"fx-head\"><span class=\"fx-name\">HEADPHONE CROSSFEED</span><input type=\"checkbox\" id=\"chk-cross\" onchange=\"sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Amount</span><span class=\"ctrl-val\" id=\"v-cross-a\">60 %</span></div><input type=\"range\" id=\"sl-cross-a\" min=\"0\" max=\"100\" value=\"60\" oninput=\"upd(this);sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Cutoff Frequency</span><span class=\"ctrl-val\" id=\"v-cross-f\">700 Hz</span></div><input type=\"range\" id=\"sl-cross-f\" min=\"500\" max=\"1000\" value=\"700\" oninput=\"upd(this);sendConfig()\"></div>\n"
"    </div>\n"
"\n"
"    <div class=\"fx-card\">\n"
"      <div class=\"fx-head\"><span class=\"fx-name\">STEREO WIDENER (M/S)</span><input type=\"checkbox\" id=\"chk-wide\" onchange=\"sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Stereo Width</span><span class=\"ctrl-val\" id=\"v-wide-w\">125 %</span></div><input type=\"range\" id=\"sl-wide-w\" min=\"0\" max=\"200\" value=\"125\" oninput=\"upd(this);sendConfig()\"></div>\n"
"    </div>\n"
"\n"
"    <div class=\"fx-card\">\n"
"      <div class=\"fx-head\"><span class=\"fx-name\">PSYCHO BASS ENHANCER</span><input type=\"checkbox\" id=\"chk-bass\" onchange=\"sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Sub Cutoff</span><span class=\"ctrl-val\" id=\"v-bass-c\">90 Hz</span></div><input type=\"range\" id=\"sl-bass-c\" min=\"60\" max=\"140\" value=\"90\" oninput=\"upd(this);sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Harmonic Drive</span><span class=\"ctrl-val\" id=\"v-bass-d\">50 %</span></div><input type=\"range\" id=\"sl-bass-d\" min=\"0\" max=\"100\" value=\"50\" oninput=\"upd(this);sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Blend</span><span class=\"ctrl-val\" id=\"v-bass-b\">40 %</span></div><input type=\"range\" id=\"sl-bass-b\" min=\"0\" max=\"100\" value=\"40\" oninput=\"upd(this);sendConfig()\"></div>\n"
"    </div>\n"
"\n"
"    <div class=\"fx-card\">\n"
"      <div class=\"fx-head\"><span class=\"fx-name\">DE-ESSER</span><input type=\"checkbox\" id=\"chk-deess\" onchange=\"sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Frequency</span><span class=\"ctrl-val\" id=\"v-deess-f\">6500 Hz</span></div><input type=\"range\" id=\"sl-deess-f\" min=\"4000\" max=\"9000\" step=\"100\" value=\"6500\" oninput=\"upd(this);sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Threshold</span><span class=\"ctrl-val\" id=\"v-deess-t\">-24 dB</span></div><input type=\"range\" id=\"sl-deess-t\" min=\"-40\" max=\"0\" value=\"-24\" oninput=\"upd(this);sendConfig()\"></div>\n"
"    </div>\n"
"\n"
"    <div class=\"fx-card\">\n"
"      <div class=\"fx-head\"><span class=\"fx-name\">PITCH SHIFTER</span><input type=\"checkbox\" id=\"chk-pitch\" onchange=\"sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Semitones</span><span class=\"ctrl-val\" id=\"v-pitch-s\">0 st</span></div><input type=\"range\" id=\"sl-pitch-s\" min=\"-12\" max=\"12\" value=\"0\" oninput=\"upd(this);sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Fine Cents</span><span class=\"ctrl-val\" id=\"v-pitch-c\">0 c</span></div><input type=\"range\" id=\"sl-pitch-c\" min=\"-100\" max=\"100\" value=\"0\" oninput=\"upd(this);sendConfig()\"></div>\n"
"    </div>\n"
"\n"
"    <div class=\"fx-card\">\n"
"      <div class=\"fx-head\"><span class=\"fx-name\">LOUDNESS / AGC</span><input type=\"checkbox\" id=\"chk-loud\" onchange=\"sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Target Level</span><span class=\"ctrl-val\" id=\"v-loud-t\">-16 dBFS</span></div><input type=\"range\" id=\"sl-loud-t\" min=\"-24\" max=\"-12\" value=\"-16\" oninput=\"upd(this);sendConfig()\"></div>\n"
"    </div>\n"
"\n"
"    <div class=\"fx-card\">\n"
"      <div class=\"fx-head\"><span class=\"fx-name\">REVERB &amp; DELAY</span><input type=\"checkbox\" id=\"chk-fx\" onchange=\"sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Delay Time</span><span class=\"ctrl-val\" id=\"v-fx-dt\">350 ms</span></div><input type=\"range\" id=\"sl-fx-dt\" min=\"20\" max=\"800\" value=\"350\" oninput=\"upd(this);sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Delay Mix</span><span class=\"ctrl-val\" id=\"v-fx-dm\">35 %</span></div><input type=\"range\" id=\"sl-fx-dm\" min=\"0\" max=\"100\" value=\"35\" oninput=\"upd(this);sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Reverb Size</span><span class=\"ctrl-val\" id=\"v-fx-rs\">75 %</span></div><input type=\"range\" id=\"sl-fx-rs\" min=\"0\" max=\"100\" value=\"75\" oninput=\"upd(this);sendConfig()\"></div>\n"
"      <div class=\"fx-ctrl\"><div class=\"ctrl-row\"><span>Reverb Mix</span><span class=\"ctrl-val\" id=\"v-fx-rm\">25 %</span></div><input type=\"range\" id=\"sl-fx-rm\" min=\"0\" max=\"100\" value=\"25\" oninput=\"upd(this);sendConfig()\"></div>\n"
"    </div>\n"
"\n"
"  </div>\n"
"</div>\n"
"\n"
"<div class=\"section\">\n"
"  <div class=\"sec-title\">// 06. PRESET MANAGEMENT //</div>\n"
"  <div class=\"row-flex\" style=\"flex-wrap:wrap;gap:8px\">\n"
"    <select class=\"select-custom\" id=\"sel-preset\"></select>\n"
"    <button onclick=\"loadPreset()\">[ LOAD ]</button>\n"
"    <button onclick=\"savePreset()\">[ SAVE ]</button>\n"
"    <button onclick=\"resetDefaults()\">[ RESET DEFAULTS ]</button>\n"
"  </div>\n"
"</div>\n"
"\n"
"<div class=\"section\">\n"
"  <div class=\"sec-title\"><span>// 07. FLASH STORAGE (LITTLEFS) //</span><span class=\"badge\" id=\"st-fs-badge\">/storage</span></div>\n"
"  <div class=\"row-flex\" style=\"flex-wrap:wrap;justify-content:space-between;align-items:center;gap:12px\">\n"
"    <div>CAPACITY: <b id=\"st-fs-total\">2.18 MB</b> &bull; FREE: <b id=\"st-fs-free\">...</b> (<span id=\"st-fs-pct\">0</span>% USED)</div>\n"
"    <div style=\"flex:1;min-width:140px;max-width:240px;height:8px;background:#000;border:1px solid var(--fg);overflow:hidden\">\n"
"      <div id=\"st-fs-bar\" style=\"height:100%;width:0%;background:var(--fg)\"></div>\n"
"    </div>\n"
"  </div>\n"
"</div>\n"
"\n"
"<footer>\n"
"  // ESP32-S3 SUPERMINI &bull; 4MB DUAL-OTA + LITTLEFS &bull; 2MB PSRAM &bull; I2S: 10 BCK / 11 DIN / 12 WS &bull; NEOPIXEL: 48 //\n"
"</footer>\n"
"\n"
"<script>\n"
"const eqFreqs = [31, 63, 125, 250, 500, 1000, 2000, 4000, 8000, 16000];\n"
"const bufSizes = [16, 32, 64, 128, 256];\n"
"const bufNames = ['16 (0.3ms)', '32 (0.7ms)', '64 (1.3ms)', '128 (2.7ms)', '256 (5.3ms)'];\n"
"let eqGains = [0,0,0,0,0,0,0,0,0,0];\n"
"let isBypass = false;\n"
"\n"
"function initEQ() {\n"
"  const container = document.getElementById('eq-controls');\n"
"  container.innerHTML = '';\n"
"  eqFreqs.forEach((f, i) => {\n"
"    const lbl = f >= 1000 ? (f/1000) + 'k' : f;\n"
"    const div = document.createElement('div');\n"
"    div.className = 'eq-band';\n"
"    div.innerHTML = `<div>${lbl}</div><input type=\"range\" min=\"-12\" max=\"12\" step=\"0.5\" value=\"0\" id=\"eq-${i}\" oninput=\"onEQChange(${i}, this.value)\"><div class=\"eq-val\" id=\"eqv-${i}\">0</div>`;\n"
"    container.appendChild(div);\n"
"  });\n"
"  drawEQ();\n"
"}\n"
"\n"
"function onEQChange(i, v) {\n"
"  eqGains[i] = parseFloat(v);\n"
"  document.getElementById(`eqv-${i}`).innerText = (v > 0 ? '+' : '') + v;\n"
"  drawEQ();\n"
"  sendConfig();\n"
"}\n"
"\n"
"function drawEQ() {\n"
"  const c = document.getElementById('eq-canvas');\n"
"  if (!c) return;\n"
"  const ctx = c.getContext('2d');\n"
"  c.width = c.clientWidth * window.devicePixelRatio;\n"
"  c.height = c.clientHeight * window.devicePixelRatio;\n"
"  ctx.scale(window.devicePixelRatio, window.devicePixelRatio);\n"
"  const w = c.clientWidth, h = c.clientHeight;\n"
"\n"
"  ctx.fillStyle = '#000000';\n"
"  ctx.fillRect(0, 0, w, h);\n"
"\n"
"  // Center 0 dB dashed reference line\n"
"  ctx.strokeStyle = '#333333';\n"
"  ctx.lineWidth = 1;\n"
"  ctx.setLineDash([4, 4]);\n"
"  ctx.beginPath();\n"
"  ctx.moveTo(0, h/2); ctx.lineTo(w, h/2);\n"
"  ctx.stroke();\n"
"  ctx.setLineDash([]);\n"
"\n"
"  // Vib-Ribbon Vector Ribbon Curve\n"
"  ctx.strokeStyle = isBypass ? '#444444' : '#ffffff';\n"
"  ctx.lineWidth = 2;\n"
"  ctx.beginPath();\n"
"  for (let x = 0; x < w; x++) {\n"
"    const normX = x / w;\n"
"    const freq = 20 * Math.pow(1000, normX);\n"
"    let totalDb = 0;\n"
"    eqFreqs.forEach((f0, i) => {\n"
"      const g = eqGains[i];\n"
"      const ratio = freq / f0;\n"
"      const bell = Math.exp(-Math.pow(Math.log(ratio), 2) / 0.5);\n"
"      totalDb += g * bell;\n"
"    });\n"
"    const y = (h/2) - (totalDb / 15) * (h/2);\n"
"    if (x === 0) ctx.moveTo(x, y); else ctx.lineTo(x, y);\n"
"  }\n"
"  ctx.stroke();\n"
"}\n"
"\n"
"function setC(chkId, en) { const el = document.getElementById(chkId); if(el) el.checked = !!en; }\n"
"function setS(slId, val) { const el = document.getElementById(slId); if(el) { el.value = val; upd(el); } }\n"
"\n"
"function setCrushProfile(p) {\n"
"  if (p === 'classic') {\n"
"    setC('chk-bc-srr', true); setC('chk-bc-q', true); setC('chk-bc-ovf', false); setC('chk-bc-dit', false);\n"
"    setS('sl-bc-rate', 8000); setS('sl-bc-bits', 8); setS('sl-bc-ovf', 0); setS('sl-bc-mix', 100);\n"
"  } else if (p === 'srr') {\n"
"    setC('chk-bc-srr', true); setC('chk-bc-q', false); setC('chk-bc-ovf', false); setC('chk-bc-dit', false);\n"
"    setS('sl-bc-rate', 6000); setS('sl-bc-bits', 16); setS('sl-bc-ovf', 0); setS('sl-bc-mix', 100);\n"
"  } else if (p === 'grit') {\n"
"    setC('chk-bc-srr', false); setC('chk-bc-q', true); setC('chk-bc-ovf', false); setC('chk-bc-dit', true);\n"
"    setS('sl-bc-rate', 48000); setS('sl-bc-bits', 12); setS('sl-bc-ovf', 0); setS('sl-bc-mix', 100);\n"
"  } else if (p === 'glitch') {\n"
"    setC('chk-bc-srr', true); setC('chk-bc-q', true); setC('chk-bc-ovf', true); setC('chk-bc-dit', false);\n"
"    setS('sl-bc-rate', 11025); setS('sl-bc-bits', 4); setS('sl-bc-ovf', 60); setS('sl-bc-mix', 85);\n"
"  }\n"
"  document.getElementById('chk-bc').checked = true;\n"
"  sendConfig();\n"
"}\n"
"\n"
"function setTapeProfile(p) {\n"
"  if (p === 'type1') {\n"
"    setS('sl-tape-d', 20); setS('sl-tape-hf', 15000); setS('sl-tape-hb', 25);\n"
"    setS('sl-tape-hs', 1); setS('sl-tape-cr', 5); setS('sl-tape-cl', 3); setS('sl-tape-wf', 10);\n"
"  } else if (p === 'type2') {\n"
"    setS('sl-tape-d', 15); setS('sl-tape-hf', 17500); setS('sl-tape-hb', 15);\n"
"    setS('sl-tape-hs', 0); setS('sl-tape-cr', 0); setS('sl-tape-cl', 0); setS('sl-tape-wf', 5);\n"
"  } else if (p === 'lofi') {\n"
"    setS('sl-tape-d', 40); setS('sl-tape-hf', 8500); setS('sl-tape-hb', 45);\n"
"    setS('sl-tape-hs', 5); setS('sl-tape-cr', 12); setS('sl-tape-cl', 6); setS('sl-tape-wf', 35);\n"
"  } else if (p === 'master') {\n"
"    setS('sl-tape-d', 25); setS('sl-tape-hf', 19000); setS('sl-tape-hb', 35);\n"
"    setS('sl-tape-hs', 0); setS('sl-tape-cr', 0); setS('sl-tape-cl', 0); setS('sl-tape-wf', 0);\n"
"  }\n"
"  document.getElementById('chk-tape').checked = true;\n"
"  sendConfig();\n"
"}\n"
"\n"
"function upd(el) {\n"
"  const id = el.id;\n"
"  const val = el.value;\n"
"  if (id === 'sl-comp-t') document.getElementById('v-comp-t').innerText = val + ' dB';\n"
"  if (id === 'sl-comp-r') document.getElementById('v-comp-r').innerText = val + ':1';\n"
"  if (id === 'sl-comp-a') document.getElementById('v-comp-a').innerText = val + ' ms';\n"
"  if (id === 'sl-comp-rel') document.getElementById('v-comp-rel').innerText = val + ' ms';\n"
"  if (id === 'sl-lim-c') document.getElementById('v-lim-c').innerText = val + ' dBFS';\n"
"  if (id === 'sl-lim-r') document.getElementById('v-lim-r').innerText = val + ' ms';\n"
"  if (id === 'sl-tape-d') document.getElementById('v-tape-d').innerText = val + ' %';\n"
"  if (id === 'sl-tape-hf') document.getElementById('v-tape-hf').innerText = (parseFloat(val) / 1000).toFixed(1) + ' kHz';\n"
"  if (id === 'sl-tape-hb') document.getElementById('v-tape-hb').innerText = val + ' %';\n"
"  if (id === 'sl-tape-hs') document.getElementById('v-tape-hs').innerText = val + ' %';\n"
"  if (id === 'sl-tape-cr') document.getElementById('v-tape-cr').innerText = val + ' %';\n"
"  if (id === 'sl-tape-cl') document.getElementById('v-tape-cl').innerText = val + ' %';\n"
"  if (id === 'sl-tape-wf') document.getElementById('v-tape-wf').innerText = val + ' %';\n"
"  if (id === 'sl-bc-rate') document.getElementById('v-bc-rate').innerText = (parseFloat(val) / 1000).toFixed(1) + ' kHz';\n"
"  if (id === 'sl-bc-bits') document.getElementById('v-bc-bits').innerText = val + ' bit';\n"
"  if (id === 'sl-bc-ovf') document.getElementById('v-bc-ovf').innerText = val + ' %';\n"
"  if (id === 'sl-bc-mix') document.getElementById('v-bc-mix').innerText = val + ' %';\n"
"  if (id === 'sl-cross-a') document.getElementById('v-cross-a').innerText = val + ' %';\n"
"  if (id === 'sl-cross-f') document.getElementById('v-cross-f').innerText = val + ' Hz';\n"
"  if (id === 'sl-wide-w') document.getElementById('v-wide-w').innerText = val + ' %';\n"
"  if (id === 'sl-bass-c') document.getElementById('v-bass-c').innerText = val + ' Hz';\n"
"  if (id === 'sl-bass-d') document.getElementById('v-bass-d').innerText = val + ' %';\n"
"  if (id === 'sl-bass-b') document.getElementById('v-bass-b').innerText = val + ' %';\n"
"  if (id === 'sl-deess-f') document.getElementById('v-deess-f').innerText = val + ' Hz';\n"
"  if (id === 'sl-deess-t') document.getElementById('v-deess-t').innerText = val + ' dB';\n"
"  if (id === 'sl-pitch-s') document.getElementById('v-pitch-s').innerText = val + ' st';\n"
"  if (id === 'sl-pitch-c') document.getElementById('v-pitch-c').innerText = val + ' c';\n"
"  if (id === 'sl-loud-t') document.getElementById('v-loud-t').innerText = val + ' dBFS';\n"
"  if (id === 'sl-fx-dt') document.getElementById('v-fx-dt').innerText = val + ' ms';\n"
"  if (id === 'sl-fx-dm') document.getElementById('v-fx-dm').innerText = val + ' %';\n"
"  if (id === 'sl-fx-rs') document.getElementById('v-fx-rs').innerText = val + ' %';\n"
"  if (id === 'sl-fx-rm') document.getElementById('v-fx-rm').innerText = val + ' %';\n"
"}\n"
"\n"
"function toggleBypass() {\n"
"  isBypass = !isBypass;\n"
"  const btn = document.getElementById('btn-bypass');\n"
"  btn.className = isBypass ? 'btn-direct active' : 'btn-direct';\n"
"  btn.innerText = isBypass ? '[ BIT-PERFECT: DIRECT ]' : '[ BIT-PERFECT: OFF ]';\n"
"  fetch('/api/config', {method:'POST', body:JSON.stringify({bit_perfect_bypass: isBypass})});\n"
"  drawEQ();\n"
"}\n"
"\n"
"function updateBuffer(idx) {\n"
"  const size = bufSizes[idx];\n"
"  document.getElementById('lbl-buf-val').innerText = bufNames[idx];\n"
"  const ms = (size / 48).toFixed(1);\n"
"  document.getElementById('lbl-lat-ms').innerText = '~' + ms + ' ms';\n"
"  fetch('/api/config', {method:'POST', body:JSON.stringify({buffer_size: size})});\n"
"}\n"
"\n"
"function sendConfig() {\n"
"  const cfg = {\n"
"    bit_perfect_bypass: isBypass,\n"
"    buffer_size: bufSizes[parseInt(document.getElementById('sl-buffer').value)],\n"
"    eq: {\n"
"      enabled: document.getElementById('chk-eq').checked,\n"
"      bands: eqGains.map(g => ({gain_db: g}))\n"
"    },\n"
"    comp: {\n"
"      enabled: document.getElementById('chk-comp').checked,\n"
"      threshold_db: parseFloat(document.getElementById('sl-comp-t').value),\n"
"      ratio: parseFloat(document.getElementById('sl-comp-r').value),\n"
"      attack_ms: parseFloat(document.getElementById('sl-comp-a').value),\n"
"      release_ms: parseFloat(document.getElementById('sl-comp-rel').value)\n"
"    },\n"
"    limiter: {\n"
"      enabled: document.getElementById('chk-limiter').checked,\n"
"      ceiling_db: parseFloat(document.getElementById('sl-lim-c').value),\n"
"      release_ms: parseFloat(document.getElementById('sl-lim-r').value)\n"
"    },\n"
"    tape: {\n"
"      enabled: document.getElementById('chk-tape').checked,\n"
"      drive: parseFloat(document.getElementById('sl-tape-d').value) / 100,\n"
"      hf_cut_hz: parseFloat(document.getElementById('sl-tape-hf').value),\n"
"      head_bump: parseFloat(document.getElementById('sl-tape-hb').value) / 100,\n"
"      hiss_level: parseFloat(document.getElementById('sl-tape-hs').value) / 100,\n"
"      click_rate: parseFloat(document.getElementById('sl-tape-cr').value) / 100,\n"
"      click_level: parseFloat(document.getElementById('sl-tape-cl').value) / 100,\n"
"      wow_flutter: parseFloat(document.getElementById('sl-tape-wf').value) / 100\n"
"    },\n"
"    bitcrusher: {\n"
"      enabled: document.getElementById('chk-bc').checked,\n"
"      enable_downsample: document.getElementById('chk-bc-srr').checked,\n"
"      enable_quantize: document.getElementById('chk-bc-q').checked,\n"
"      enable_overflow: document.getElementById('chk-bc-ovf').checked,\n"
"      dither: document.getElementById('chk-bc-dit').checked,\n"
"      bit_depth: parseInt(document.getElementById('sl-bc-bits').value),\n"
"      downsample_rate: parseFloat(document.getElementById('sl-bc-rate').value),\n"
"      overflow_intensity: parseFloat(document.getElementById('sl-bc-ovf').value) / 100,\n"
"      mix: parseFloat(document.getElementById('sl-bc-mix').value) / 100\n"
"    },\n"
"    crossfeed: {\n"
"      enabled: document.getElementById('chk-cross').checked,\n"
"      amount: parseFloat(document.getElementById('sl-cross-a').value) / 100,\n"
"      cutoff_hz: parseFloat(document.getElementById('sl-cross-f').value)\n"
"    },\n"
"    widener: {\n"
"      enabled: document.getElementById('chk-wide').checked,\n"
"      width: parseFloat(document.getElementById('sl-wide-w').value) / 100\n"
"    },\n"
"    bass: {\n"
"      enabled: document.getElementById('chk-bass').checked,\n"
"      cutoff_hz: parseFloat(document.getElementById('sl-bass-c').value),\n"
"      drive: parseFloat(document.getElementById('sl-bass-d').value) / 100,\n"
"      blend: parseFloat(document.getElementById('sl-bass-b').value) / 100\n"
"    },\n"
"    deesser: {\n"
"      enabled: document.getElementById('chk-deess').checked,\n"
"      freq: parseFloat(document.getElementById('sl-deess-f').value),\n"
"      threshold_db: parseFloat(document.getElementById('sl-deess-t').value)\n"
"    },\n"
"    pitch: {\n"
"      enabled: document.getElementById('chk-pitch').checked,\n"
"      semitones: parseInt(document.getElementById('sl-pitch-s').value),\n"
"      cents: parseInt(document.getElementById('sl-pitch-c').value)\n"
"    },\n"
"    loudness: {\n"
"      enabled: document.getElementById('chk-loud').checked,\n"
"      target_db: parseFloat(document.getElementById('sl-loud-t').value)\n"
"    },\n"
"    fx: {\n"
"      delay_enabled: document.getElementById('chk-fx').checked,\n"
"      delay_time_ms: parseFloat(document.getElementById('sl-fx-dt').value),\n"
"      delay_mix: parseFloat(document.getElementById('sl-fx-dm').value) / 100,\n"
"      reverb_enabled: document.getElementById('chk-fx').checked,\n"
"      reverb_room_size: parseFloat(document.getElementById('sl-fx-rs').value) / 100,\n"
"      reverb_mix: parseFloat(document.getElementById('sl-fx-rm').value) / 100\n"
"    }\n"
"  };\n"
"  fetch('/api/config', {method:'POST', body:JSON.stringify(cfg)});\n"
"}\n"
"\n"
"function pollVU() {\n"
"  fetch('/api/vu').then(r => r.json()).then(d => {\n"
"    function setM(id, valId, db) {\n"
"      const pct = Math.max(0, Math.min(100, (db + 60) * (100 / 60)));\n"
"      const el = document.getElementById(id);\n"
"      if (el) {\n"
"        el.style.width = pct + '%';\n"
"        el.className = db >= -0.1 ? 'meter-fill clip' : 'meter-fill';\n"
"      }\n"
"      const elV = document.getElementById(valId);\n"
"      if (elV) elV.innerText = db <= -60 ? '-inf' : db.toFixed(1);\n"
"    }\n"
"    setM('m-in-l', 'v-in-l', d.in_peak_l);\n"
"    setM('m-in-r', 'v-in-r', d.in_peak_r);\n"
"    setM('m-out-l', 'v-out-l', d.out_peak_l);\n"
"    setM('m-out-r', 'v-out-r', d.out_peak_r);\n"
"  }).catch(() => {});\n"
"}\n"
"\n"
"function loadPresetsList() {\n"
"  fetch('/api/presets').then(r => r.json()).then(presets => {\n"
"    const sel = document.getElementById('sel-preset');\n"
"    if (!sel) return;\n"
"    sel.innerHTML = '';\n"
"    presets.forEach((p, idx) => {\n"
"      const opt = document.createElement('option');\n"
"      opt.value = idx;\n"
"      opt.text = p.name;\n"
"      sel.appendChild(opt);\n"
"    });\n"
"  });\n"
"}\n"
"\n"
"function loadPreset() {\n"
"  const idx = document.getElementById('sel-preset').value;\n"
"  fetch('/api/presets/load', {method:'POST', body:JSON.stringify({index: parseInt(idx)})}).then(() => loadConfig());\n"
"}\n"
"\n"
"function loadConfig() {\n"
"  fetch('/api/config').then(r => r.json()).then(cfg => {\n"
"    if (cfg.bit_perfect_bypass !== undefined) {\n"
"      isBypass = cfg.bit_perfect_bypass;\n"
"      const btn = document.getElementById('btn-bypass');\n"
"      if (btn) {\n"
"        btn.className = isBypass ? 'btn-direct active' : 'btn-direct';\n"
"        btn.innerText = isBypass ? '[ BIT-PERFECT: DIRECT ]' : '[ BIT-PERFECT: OFF ]';\n"
"      }\n"
"    }\n"
"    if (cfg.buffer_size) {\n"
"      const idx = bufSizes.indexOf(cfg.buffer_size);\n"
"      if (idx !== -1) {\n"
"        const sl = document.getElementById('sl-buffer');\n"
"        if (sl) sl.value = idx;\n"
"        const lblB = document.getElementById('lbl-buf-val');\n"
"        if (lblB) lblB.innerText = bufNames[idx];\n"
"        const lblL = document.getElementById('lbl-lat-ms');\n"
"        if (lblL) lblL.innerText = '~' + (cfg.buffer_size / 48).toFixed(1) + ' ms';\n"
"      }\n"
"    }\n"
"    if (cfg.eq && cfg.eq.bands) {\n"
"      const chk = document.getElementById('chk-eq');\n"
"      if (chk) chk.checked = cfg.eq.enabled;\n"
"      cfg.eq.bands.forEach((b, i) => {\n"
"        if (i < 10) {\n"
"          eqGains[i] = b.gain_db;\n"
"          const sl = document.getElementById(`eq-${i}`);\n"
"          if (sl) sl.value = b.gain_db;\n"
"          const v = document.getElementById(`eqv-${i}`);\n"
"          if (v) v.innerText = (b.gain_db > 0 ? '+' : '') + b.gain_db;\n"
"        }\n"
"      });\n"
"      drawEQ();\n"
"    }\n"
"    if (cfg.comp) {\n"
"      setC('chk-comp', cfg.comp.enabled);\n"
"      setS('sl-comp-t', cfg.comp.threshold_db);\n"
"      setS('sl-comp-r', cfg.comp.ratio);\n"
"      setS('sl-comp-a', cfg.comp.attack_ms);\n"
"      setS('sl-comp-rel', cfg.comp.release_ms);\n"
"    }\n"
"    if (cfg.limiter) {\n"
"      setC('chk-limiter', cfg.limiter.enabled);\n"
"      setS('sl-lim-c', cfg.limiter.ceiling_db);\n"
"      setS('sl-lim-r', cfg.limiter.release_ms);\n"
"    }\n"
"    if (cfg.tape) {\n"
"      setC('chk-tape', cfg.tape.enabled);\n"
"      setS('sl-tape-d', Math.round(cfg.tape.drive * 100));\n"
"      setS('sl-tape-hf', Math.round(cfg.tape.hf_cut_hz));\n"
"      setS('sl-tape-hb', Math.round(cfg.tape.head_bump * 100));\n"
"      setS('sl-tape-hs', Math.round(cfg.tape.hiss_level * 100));\n"
"      setS('sl-tape-cr', Math.round(cfg.tape.click_rate * 100));\n"
"      setS('sl-tape-cl', Math.round(cfg.tape.click_level * 100));\n"
"      setS('sl-tape-wf', Math.round(cfg.tape.wow_flutter * 100));\n"
"    }\n"
"    if (cfg.bitcrusher) {\n"
"      setC('chk-bc', cfg.bitcrusher.enabled);\n"
"      setC('chk-bc-srr', cfg.bitcrusher.enable_downsample);\n"
"      setC('chk-bc-q', cfg.bitcrusher.enable_quantize);\n"
"      setC('chk-bc-ovf', cfg.bitcrusher.enable_overflow);\n"
"      setC('chk-bc-dit', cfg.bitcrusher.dither);\n"
"      setS('sl-bc-bits', cfg.bitcrusher.bit_depth);\n"
"      setS('sl-bc-rate', Math.round(cfg.bitcrusher.downsample_rate));\n"
"      setS('sl-bc-ovf', Math.round(cfg.bitcrusher.overflow_intensity * 100));\n"
"      setS('sl-bc-mix', Math.round(cfg.bitcrusher.mix * 100));\n"
"    }\n"
"    if (cfg.crossfeed) {\n"
"      setC('chk-cross', cfg.crossfeed.enabled);\n"
"      setS('sl-cross-a', Math.round(cfg.crossfeed.amount * 100));\n"
"      setS('sl-cross-f', Math.round(cfg.crossfeed.cutoff_hz));\n"
"    }\n"
"    if (cfg.widener) {\n"
"      setC('chk-wide', cfg.widener.enabled);\n"
"      setS('sl-wide-w', Math.round(cfg.widener.width * 100));\n"
"    }\n"
"    if (cfg.bass) {\n"
"      setC('chk-bass', cfg.bass.enabled);\n"
"      setS('sl-bass-c', Math.round(cfg.bass.cutoff_hz));\n"
"      setS('sl-bass-d', Math.round(cfg.bass.drive * 100));\n"
"      setS('sl-bass-b', Math.round(cfg.bass.blend * 100));\n"
"    }\n"
"    if (cfg.deesser) {\n"
"      setC('chk-deess', cfg.deesser.enabled);\n"
"      setS('sl-deess-f', Math.round(cfg.deesser.freq));\n"
"      setS('sl-deess-t', Math.round(cfg.deesser.threshold_db));\n"
"    }\n"
"    if (cfg.pitch) {\n"
"      setC('chk-pitch', cfg.pitch.enabled);\n"
"      setS('sl-pitch-s', cfg.pitch.semitones);\n"
"      setS('sl-pitch-c', cfg.pitch.cents);\n"
"    }\n"
"    if (cfg.loudness) {\n"
"      setC('chk-loud', cfg.loudness.enabled);\n"
"      setS('sl-loud-t', Math.round(cfg.loudness.target_db));\n"
"    }\n"
"    if (cfg.fx) {\n"
"      setC('chk-fx', cfg.fx.delay_enabled || cfg.fx.reverb_enabled);\n"
"      setS('sl-fx-dt', Math.round(cfg.fx.delay_time_ms));\n"
"      setS('sl-fx-dm', Math.round(cfg.fx.delay_mix * 100));\n"
"      setS('sl-fx-rs', Math.round(cfg.fx.reverb_room_size * 100));\n"
"      setS('sl-fx-rm', Math.round(cfg.fx.reverb_mix * 100));\n"
"    }\n"
"  }).catch(() => {});\n"
"}\n"
"\n"
"function pollStatus() {\n"
"  fetch('/api/status').then(r => r.json()).then(st => {\n"
"    if (st.sample_rate) {\n"
"      const el = document.getElementById('st-rate');\n"
"      if (el) el.innerText = (st.sample_rate / 1000).toFixed(1) + ' kHz / ' + st.bit_depth + '-bit' + (st.is_streaming ? ' [PLAY]' : ' [IDLE]');\n"
"    }\n"
"  }).catch(() => {});\n"
"}\n"
"\n"
"function savePreset() {\n"
"  const idx = document.getElementById('sel-preset').value;\n"
"  const name = prompt('Preset name:', 'Custom Preset');\n"
"  if (name) {\n"
"    fetch('/api/presets/save', {method:'POST', body:JSON.stringify({index: parseInt(idx), name: name})}).then(() => loadPresetsList());\n"
"  }\n"
"}\n"
"\n"
"function resetDefaults() {\n"
"  if (confirm('Reset all presets to factory defaults?')) {\n"
"    fetch('/api/presets/reset', {method:'POST'}).then(() => loadConfig());\n"
"  }\n"
"}\n"
"\n"
"let ledMode = 1;\n"
"let ledBrightness = 50;\n"
"const ledModeNames = ['OFF', 'VU PEAK', 'BASS PULSE', 'RAINBOW', 'WARM TUBE', 'STATUS'];\n"
"\n"
"function updateLEDUI() {\n"
"  const lbl = document.getElementById('lbl-led-mode');\n"
"  if (lbl) lbl.innerText = ledModeNames[ledMode] || 'OFF';\n"
"  const sl = document.getElementById('sl-led-br');\n"
"  if (sl) sl.value = ledBrightness;\n"
"  const brLbl = document.getElementById('lbl-led-br');\n"
"  if (brLbl) brLbl.innerText = ledBrightness + '%';\n"
"  for (let i = 0; i <= 5; i++) {\n"
"    const btn = document.getElementById('btn-led-' + i);\n"
"    if (btn) {\n"
"      if (i === ledMode) {\n"
"        btn.style.background = 'var(--fg)';\n"
"        btn.style.color = 'var(--bg)';\n"
"        btn.style.fontWeight = 'bold';\n"
"      } else {\n"
"        btn.style.background = 'var(--bg)';\n"
"        btn.style.color = 'var(--fg)';\n"
"        btn.style.fontWeight = 'normal';\n"
"      }\n"
"    }\n"
"  }\n"
"}\n"
"\n"
"function setLEDMode(m) {\n"
"  ledMode = m;\n"
"  updateLEDUI();\n"
"  sendLEDConfig();\n"
"}\n"
"\n"
"function sendLEDConfig() {\n"
"  ledBrightness = parseInt(document.getElementById('sl-led-br').value) || 50;\n"
"  fetch('/api/led', {\n"
"    method: 'POST',\n"
"    headers: { 'Content-Type': 'application/json' },\n"
"    body: JSON.stringify({ mode: ledMode, brightness: ledBrightness })\n"
"  }).catch(() => {});\n"
"}\n"
"\n"
"function loadLEDConfig() {\n"
"  fetch('/api/led')\n"
"    .then(r => r.json())\n"
"    .then(d => {\n"
"      if (d) {\n"
"        if (typeof d.mode === 'number') ledMode = d.mode;\n"
"        if (typeof d.brightness === 'number') ledBrightness = d.brightness;\n"
"        updateLEDUI();\n"
"      }\n"
"    }).catch(() => {});\n"
"}\n"
"\n"
"function pollStorage() {\n"
"  fetch('/api/storage')\n"
"    .then(r => r.json())\n"
"    .then(d => {\n"
"      if (d && d.mounted) {\n"
"        const mb = (d.total_bytes / (1024*1024)).toFixed(2);\n"
"        const freeKb = Math.round(d.free_bytes / 1024);\n"
"        const elT = document.getElementById('st-fs-total'); if (elT) elT.innerText = mb + ' MB';\n"
"        const elF = document.getElementById('st-fs-free'); if (elF) elF.innerText = freeKb + ' KB';\n"
"        const pct = (d.percent_used || 0).toFixed(1);\n"
"        const elP = document.getElementById('st-fs-pct'); if (elP) elP.innerText = pct;\n"
"        const elB = document.getElementById('st-fs-bar'); if (elB) elB.style.width = pct + '%';\n"
"        const elBd = document.getElementById('st-fs-badge'); if (elBd) elBd.innerText = 'MOUNTED: ' + d.base_path;\n"
"      }\n"
"    }).catch(() => {});\n"
"}\n"
"\n"
"window.onload = function() {\n"
"  initEQ();\n"
"  loadPresetsList();\n"
"  loadConfig();\n"
"  loadLEDConfig();\n"
"  pollStatus();\n"
"  pollStorage();\n"
"  setInterval(pollVU, 200);\n"
"  setInterval(pollStatus, 1500);\n"
"  setInterval(pollStorage, 5000);\n"
"};\n"
"</script>\n"
"</body>\n"
"</html>\n";

#endif /* _WEB_UI_HTML_H_ */
